# Additional 47 schools to add to evaluator.py (ranks 54-100)
# Insert these into the _load_schools_data() method before the closing brace

ADDITIONAL_SCHOOLS = {
    # 54-60
    "University of Washington": {
        "rank": 54,
        "acceptance_rate": 0.478,
        "avg_gpa_unweighted": 3.75,
        "avg_gpa_weighted": 3.99,
        "sat_range": (1220, 1470),
        "sat_25th": 1220, "sat_75th": 1470,
        "act_range": (27, 33),
        "selectivity": "competitive",
        "available_rounds": ["EA", "RD"],
        "values_demonstrated_interest": False,
        "need_blind": False
    },
    "University of Connecticut": {
        "rank": 54,
        "acceptance_rate": 0.556,
        "avg_gpa_unweighted": 3.72,
        "avg_gpa_weighted": 3.96,
        "sat_range": (1230, 1430),
        "sat_25th": 1230, "sat_75th": 1430,
        "act_range": (27, 32),
        "selectivity": "competitive",
        "available_rounds": ["EA", "RD"],
        "values_demonstrated_interest": True,
        "need_blind": False
    },
    "Rensselaer Polytechnic Institute": {
        "rank": 54,
        "acceptance_rate": 0.534,
        "avg_gpa_unweighted": 3.74,
        "avg_gpa_weighted": 3.98,
        "sat_range": (1330, 1510),
        "sat_25th": 1330, "sat_75th": 1510,
        "act_range": (30, 34),
        "selectivity": "very_competitive",
        "available_rounds": ["ED1", "ED2", "RD"],
        "values_demonstrated_interest": True,
        "need_blind": False
    },
    "Santa Clara University": {
        "rank": 54,
        "acceptance_rate": 0.524,
        "avg_gpa_unweighted": 3.70,
        "avg_gpa_weighted": 3.94,
        "sat_range": (1280, 1470),
        "sat_25th": 1280, "sat_75th": 1470,
        "act_range": (28, 33),
        "selectivity": "competitive",
        "available_rounds": ["EA", "RD"],
        "values_demonstrated_interest": True,
        "need_blind": False
    },
    "Syracuse University": {
        "rank": 58,
        "acceptance_rate": 0.517,
        "avg_gpa_unweighted": 3.68,
        "avg_gpa_weighted": 3.92,
        "sat_range": (1180, 1380),
        "sat_25th": 1180, "sat_75th": 1380,
        "act_range": (26, 31),
        "selectivity": "competitive",
        "available_rounds": ["ED", "EA", "RD"],
        "values_demonstrated_interest": True,
        "need_blind": False
    },
    "University of Maryland": {
        "rank": 58,
        "acceptance_rate": 0.447,
        "avg_gpa_unweighted": 3.77,
        "avg_gpa_weighted": 4.01,
        "sat_range": (1300, 1490),
        "sat_25th": 1300, "sat_75th": 1490,
        "act_range": (29, 34),
        "selectivity": "very_competitive",
        "available_rounds": ["EA", "RD"],
        "values_demonstrated_interest": False,
        "need_blind": False
    },
    "University of Pittsburgh": {
        "rank": 58,
        "acceptance_rate": 0.493,
        "avg_gpa_unweighted": 3.73,
        "avg_gpa_weighted": 3.97,
        "sat_range": (1250, 1450),
        "sat_25th": 1250, "sat_75th": 1450,
        "act_range": (28, 33),
        "selectivity": "competitive",
        "available_rounds": ["EA", "RD"],
        "values_demonstrated_interest": True,
        "need_blind": False
    },
    # 61-70
    "Rutgers University": {
        "rank": 61,
        "acceptance_rate": 0.664,
        "avg_gpa_unweighted": 3.68,
        "avg_gpa_weighted": 3.92,
        "sat_range": (1190, 1420),
        "sat_25th": 1190, "sat_75th": 1420,
        "act_range": (26, 32),
        "selectivity": "competitive",
        "available_rounds": ["EA", "RD"],
        "values_demonstrated_interest": False,
        "need_blind": False
    },
    "Penn State University": {
        "rank": 61,
        "acceptance_rate": 0.549,
        "avg_gpa_unweighted": 3.67,
        "avg_gpa_weighted": 3.91,
        "sat_range": (1160, 1370),
        "sat_25th": 1160, "sat_75th": 1370,
        "act_range": (26, 31),
        "selectivity": "competitive",
        "available_rounds": ["EA", "RD"],
        "values_demonstrated_interest": False,
        "need_blind": False
    },
    "University of Minnesota": {
        "rank": 63,
        "acceptance_rate": 0.757,
        "avg_gpa_unweighted": 3.70,
        "avg_gpa_weighted": 3.94,
        "sat_range": (1270, 1480),
        "sat_25th": 1270, "sat_75th": 1480,
        "act_range": (27, 32),
        "selectivity": "competitive",
        "available_rounds": ["EA", "RD"],
        "values_demonstrated_interest": False,
        "need_blind": False
    },
    "Texas A&M University": {
        "rank": 63,
        "acceptance_rate": 0.632,
        "avg_gpa_unweighted": 3.68,
        "avg_gpa_weighted": 3.92,
        "sat_range": (1160, 1390),
        "sat_25th": 1160, "sat_75th": 1390,
        "act_range": (25, 31),
        "selectivity": "competitive",
        "available_rounds": ["EA", "RD"],
        "values_demonstrated_interest": False,
        "need_blind": False
    },
    "Virginia Tech": {
        "rank": 63,
        "acceptance_rate": 0.657,
        "avg_gpa_unweighted": 3.72,
        "avg_gpa_weighted": 3.96,
        "sat_range": (1180, 1390),
        "sat_25th": 1180, "sat_75th": 1390,
        "act_range": (26, 32),
        "selectivity": "competitive",
        "available_rounds": ["ED", "EA", "RD"],
        "values_demonstrated_interest": True,
        "need_blind": False
    },
    "Worcester Polytechnic Institute": {
        "rank": 66,
        "acceptance_rate": 0.574,
        "avg_gpa_unweighted": 3.71,
        "avg_gpa_weighted": 3.95,
        "sat_range": (1320, 1490),
        "sat_25th": 1320, "sat_75th": 1490,
        "act_range": (30, 34),
        "selectivity": "competitive",
        "available_rounds": ["ED1", "ED2", "EA", "RD"],
        "values_demonstrated_interest": True,
        "need_blind": False
    },
    "Clemson University": {
        "rank": 67,
        "acceptance_rate": 0.434,
        "avg_gpa_unweighted": 3.74,
        "avg_gpa_weighted": 3.98,
        "sat_range": (1230, 1410),
        "sat_25th": 1230, "sat_75th": 1410,
        "act_range": (27, 32),
        "selectivity": "competitive",
        "available_rounds": ["EA", "RD"],
        "values_demonstrated_interest": True,
        "need_blind": False
    },
    "Fordham University": {
        "rank": 67,
        "acceptance_rate": 0.543,
        "avg_gpa_unweighted": 3.66,
        "avg_gpa_weighted": 3.90,
        "sat_range": (1280, 1460),
        "sat_25th": 1280, "sat_75th": 1460,
        "act_range": (29, 33),
        "selectivity": "competitive",
        "available_rounds": ["ED", "EA", "RD"],
        "values_demonstrated_interest": True,
        "need_blind": False
    },
    "Southern Methodist University": {
        "rank": 67,
        "acceptance_rate": 0.521,
        "avg_gpa_unweighted": 3.69,
        "avg_gpa_weighted": 3.93,
        "sat_range": (1290, 1470),
        "sat_25th": 1290, "sat_75th": 1470,
        "act_range": (29, 33),
        "selectivity": "competitive",
        "available_rounds": ["ED1", "ED2", "EA", "RD"],
        "values_demonstrated_interest": True,
        "need_blind": False
    },
    "University of Massachusetts Amherst": {
        "rank": 67,
        "acceptance_rate": 0.644,
        "avg_gpa_unweighted": 3.70,
        "avg_gpa_weighted": 3.94,
        "sat_range": (1230, 1440),
        "sat_25th": 1230, "sat_75th": 1440,
        "act_range": (27, 32),
        "selectivity": "competitive",
        "available_rounds": ["EA", "RD"],
        "values_demonstrated_interest": False,
        "need_blind": False
    },
    # 71-80
    "Indiana University Bloomington": {
        "rank": 71,
        "acceptance_rate": 0.824,
        "avg_gpa_unweighted": 3.65,
        "avg_gpa_weighted": 3.89,
        "sat_range": (1160, 1370),
        "sat_25th": 1160, "sat_75th": 1370,
        "act_range": (26, 32),
        "selectivity": "competitive",
        "available_rounds": ["EA", "RD"],
        "values_demonstrated_interest": False,
        "need_blind": False
    },
    "Michigan State University": {
        "rank": 71,
        "acceptance_rate": 0.883,
        "avg_gpa_unweighted": 3.64,
        "avg_gpa_weighted": 3.88,
        "sat_range": (1100, 1320),
        "sat_25th": 1100, "sat_75th": 1320,
        "act_range": (24, 30),
        "selectivity": "competitive",
        "available_rounds": ["EA", "RD"],
        "values_demonstrated_interest": False,
        "need_blind": False
    },
    "Stevens Institute of Technology": {
        "rank": 71,
        "acceptance_rate": 0.466,
        "avg_gpa_unweighted": 3.72,
        "avg_gpa_weighted": 3.96,
        "sat_range": (1330, 1500),
        "sat_25th": 1330, "sat_75th": 1500,
        "act_range": (30, 34),
        "selectivity": "competitive",
        "available_rounds": ["ED1", "ED2", "RD"],
        "values_demonstrated_interest": True,
        "need_blind": False
    },
    "University of Delaware": {
        "rank": 71,
        "acceptance_rate": 0.738,
        "avg_gpa_unweighted": 3.66,
        "avg_gpa_weighted": 3.90,
        "sat_range": (1180, 1370),
        "sat_25th": 1180, "sat_75th": 1370,
        "act_range": (26, 31),
        "selectivity": "competitive",
        "available_rounds": ["EA", "RD"],
        "values_demonstrated_interest": True,
        "need_blind": False
    },
    "University of Miami": {
        "rank": 71,
        "acceptance_rate": 0.192,
        "avg_gpa_unweighted": 3.75,
        "avg_gpa_weighted": 3.99,
        "sat_range": (1280, 1450),
        "sat_25th": 1280, "sat_75th": 1450,
        "act_range": (29, 33),
        "selectivity": "very_competitive",
        "available_rounds": ["ED", "EA", "RD"],
        "values_demonstrated_interest": True,
        "need_blind": False
    },
    "Baylor University": {
        "rank": 76,
        "acceptance_rate": 0.459,
        "avg_gpa_unweighted": 3.68,
        "avg_gpa_weighted": 3.92,
        "sat_range": (1200, 1390),
        "sat_25th": 1200, "sat_75th": 1390,
        "act_range": (27, 32),
        "selectivity": "competitive",
        "available_rounds": ["EA", "RD"],
        "values_demonstrated_interest": True,
        "need_blind": False
    },
    "Brigham Young University": {
        "rank": 76,
        "acceptance_rate": 0.673,
        "avg_gpa_unweighted": 3.72,
        "avg_gpa_weighted": 3.96,
        "sat_range": (1190, 1410),
        "sat_25th": 1190, "sat_75th": 1410,
        "act_range": (26, 32),
        "selectivity": "competitive",
        "available_rounds": ["EA", "RD"],
        "values_demonstrated_interest": False,
        "need_blind": False
    },
    "Gonzaga University": {
        "rank": 76,
        "acceptance_rate": 0.704,
        "avg_gpa_unweighted": 3.67,
        "avg_gpa_weighted": 3.91,
        "sat_range": (1190, 1390),
        "sat_25th": 1190, "sat_75th": 1390,
        "act_range": (26, 31),
        "selectivity": "competitive",
        "available_rounds": ["EA", "RD"],
        "values_demonstrated_interest": True,
        "need_blind": False
    },
    "North Carolina State University": {
        "rank": 76,
        "acceptance_rate": 0.474,
        "avg_gpa_unweighted": 3.70,
        "avg_gpa_weighted": 3.94,
        "sat_range": (1240, 1430),
        "sat_25th": 1240, "sat_75th": 1430,
        "act_range": (27, 32),
        "selectivity": "competitive",
        "available_rounds": ["EA", "RD"],
        "values_demonstrated_interest": False,
        "need_blind": False
    },
    "University of Iowa": {
        "rank": 76,
        "acceptance_rate": 0.863,
        "avg_gpa_unweighted": 3.63,
        "avg_gpa_weighted": 3.87,
        "sat_range": (1130, 1350),
        "sat_25th": 1130, "sat_75th": 1350,
        "act_range": (24, 30),
        "selectivity": "competitive",
        "available_rounds": ["EA", "RD"],
        "values_demonstrated_interest": False,
        "need_blind": False
    },
    # 81-90
    "American University": {
        "rank": 81,
        "acceptance_rate": 0.640,
        "avg_gpa_unweighted": 3.65,
        "avg_gpa_weighted": 3.89,
        "sat_range": (1240, 1420),
        "sat_25th": 1240, "sat_75th": 1420,
        "act_range": (27, 32),
        "selectivity": "competitive",
        "available_rounds": ["ED1", "ED2", "RD"],
        "values_demonstrated_interest": True,
        "need_blind": False
    },
    "Loyola Marymount University": {
        "rank": 81,
        "acceptance_rate": 0.504,
        "avg_gpa_unweighted": 3.68,
        "avg_gpa_weighted": 3.92,
        "sat_range": (1230, 1410),
        "sat_25th": 1230, "sat_75th": 1410,
        "act_range": (27, 32),
        "selectivity": "competitive",
        "available_rounds": ["EA", "RD"],
        "values_demonstrated_interest": True,
        "need_blind": False
    },
    "Marquette University": {
        "rank": 81,
        "acceptance_rate": 0.872,
        "avg_gpa_unweighted": 3.62,
        "avg_gpa_weighted": 3.86,
        "sat_range": (1140, 1350),
        "sat_25th": 1140, "sat_75th": 1350,
        "act_range": (25, 30),
        "selectivity": "competitive",
        "available_rounds": ["EA", "RD"],
        "values_demonstrated_interest": True,
        "need_blind": False
    },
    "University of California Santa Cruz": {
        "rank": 81,
        "acceptance_rate": 0.473,
        "avg_gpa_unweighted": 3.68,
        "avg_gpa_weighted": 3.92,
        "sat_range": (1170, 1400),
        "sat_25th": 1170, "sat_75th": 1400,
        "act_range": (25, 31),
        "selectivity": "competitive",
        "available_rounds": ["RD"],
        "values_demonstrated_interest": False,
        "need_blind": False
    },
    "University of San Diego": {
        "rank": 81,
        "acceptance_rate": 0.534,
        "avg_gpa_unweighted": 3.69,
        "avg_gpa_weighted": 3.93,
        "sat_range": (1220, 1400),
        "sat_25th": 1220, "sat_75th": 1400,
        "act_range": (27, 31),
        "selectivity": "competitive",
        "available_rounds": ["EA", "RD"],
        "values_demonstrated_interest": True,
        "need_blind": False
    },
    "University of Tulsa": {
        "rank": 81,
        "acceptance_rate": 0.693,
        "avg_gpa_unweighted": 3.64,
        "avg_gpa_weighted": 3.88,
        "sat_range": (1180, 1400),
        "sat_25th": 1180, "sat_75th": 1400,
        "act_range": (26, 32),
        "selectivity": "competitive",
        "available_rounds": ["EA", "RD"],
        "values_demonstrated_interest": True,
        "need_blind": False
    },
    "Auburn University": {
        "rank": 87,
        "acceptance_rate": 0.710,
        "avg_gpa_unweighted": 3.66,
        "avg_gpa_weighted": 3.90,
        "sat_range": (1160, 1350),
        "sat_25th": 1160, "sat_75th": 1350,
        "act_range": (25, 31),
        "selectivity": "competitive",
        "available_rounds": ["EA", "RD"],
        "values_demonstrated_interest": False,
        "need_blind": False
    },
    "Colorado School of Mines": {
        "rank": 87,
        "acceptance_rate": 0.580,
        "avg_gpa_unweighted": 3.74,
        "avg_gpa_weighted": 3.98,
        "sat_range": (1280, 1470),
        "sat_25th": 1280, "sat_75th": 1470,
        "act_range": (29, 33),
        "selectivity": "competitive",
        "available_rounds": ["EA", "RD"],
        "values_demonstrated_interest": True,
        "need_blind": False
    },
    "University of Denver": {
        "rank": 87,
        "acceptance_rate": 0.596,
        "avg_gpa_unweighted": 3.67,
        "avg_gpa_weighted": 3.91,
        "sat_range": (1220, 1410),
        "sat_25th": 1220, "sat_75th": 1410,
        "act_range": (27, 32),
        "selectivity": "competitive",
        "available_rounds": ["ED", "EA", "RD"],
        "values_demonstrated_interest": True,
        "need_blind": False
    },
    "University of Vermont": {
        "rank": 87,
        "acceptance_rate": 0.603,
        "avg_gpa_unweighted": 3.66,
        "avg_gpa_weighted": 3.90,
        "sat_range": (1200, 1390),
        "sat_25th": 1200, "sat_75th": 1390,
        "act_range": (26, 31),
        "selectivity": "competitive",
        "available_rounds": ["EA", "RD"],
        "values_demonstrated_interest": True,
        "need_blind": False
    },
    # 91-100
    "Binghamton University": {
        "rank": 91,
        "acceptance_rate": 0.424,
        "avg_gpa_unweighted": 3.71,
        "avg_gpa_weighted": 3.95,
        "sat_range": (1300, 1450),
        "sat_25th": 1300, "sat_75th": 1450,
        "act_range": (29, 33),
        "selectivity": "competitive",
        "available_rounds": ["EA", "RD"],
        "values_demonstrated_interest": False,
        "need_blind": False
    },
    "Drexel University": {
        "rank": 91,
        "acceptance_rate": 0.797,
        "avg_gpa_unweighted": 3.62,
        "avg_gpa_weighted": 3.86,
        "sat_range": (1180, 1390),
        "sat_25th": 1180, "sat_75th": 1390,
        "act_range": (26, 32),
        "selectivity": "competitive",
        "available_rounds": ["EA", "RD"],
        "values_demonstrated_interest": True,
        "need_blind": False
    },
    "Florida State University": {
        "rank": 91,
        "acceptance_rate": 0.253,
        "avg_gpa_unweighted": 3.73,
        "avg_gpa_weighted": 3.97,
        "sat_range": (1210, 1360),
        "sat_25th": 1210, "sat_75th": 1360,
        "act_range": (27, 31),
        "selectivity": "competitive",
        "available_rounds": ["EA", "RD"],
        "values_demonstrated_interest": False,
        "need_blind": False
    },
    "St. Louis University": {
        "rank": 91,
        "acceptance_rate": 0.854,
        "avg_gpa_unweighted": 3.63,
        "avg_gpa_weighted": 3.87,
        "sat_range": (1160, 1370),
        "sat_25th": 1160, "sat_75th": 1370,
        "act_range": (25, 31),
        "selectivity": "competitive",
        "available_rounds": ["EA", "RD"],
        "values_demonstrated_interest": True,
        "need_blind": False
    },
    "Stony Brook University": {
        "rank": 91,
        "acceptance_rate": 0.492,
        "avg_gpa_unweighted": 3.69,
        "avg_gpa_weighted": 3.93,
        "sat_range": (1280, 1470),
        "sat_25th": 1280, "sat_75th": 1470,
        "act_range": (28, 33),
        "selectivity": "competitive",
        "available_rounds": ["EA", "RD"],
        "values_demonstrated_interest": False,
        "need_blind": False
    },
    "Texas Christian University": {
        "rank": 91,
        "acceptance_rate": 0.517,
        "avg_gpa_unweighted": 3.67,
        "avg_gpa_weighted": 3.91,
        "sat_range": (1160, 1350),
        "sat_25th": 1160, "sat_75th": 1350,
        "act_range": (26, 31),
        "selectivity": "competitive",
        "available_rounds": ["ED", "EA", "RD"],
        "values_demonstrated_interest": True,
        "need_blind": False
    },
    "University of Alabama": {
        "rank": 91,
        "acceptance_rate": 0.803,
        "avg_gpa_unweighted": 3.64,
        "avg_gpa_weighted": 3.88,
        "sat_range": (1060, 1280),
        "sat_25th": 1060, "sat_75th": 1280,
        "act_range": (23, 31),
        "selectivity": "competitive",
        "available_rounds": ["EA", "RD"],
        "values_demonstrated_interest": False,
        "need_blind": False
    },
    "University of California Riverside": {
        "rank": 91,
        "acceptance_rate": 0.693,
        "avg_gpa_unweighted": 3.64,
        "avg_gpa_weighted": 3.88,
        "sat_range": (1130, 1380),
        "sat_25th": 1130, "sat_75th": 1380,
        "act_range": (24, 31),
        "selectivity": "competitive",
        "available_rounds": ["RD"],
        "values_demonstrated_interest": False,
        "need_blind": False
    },
    "University of Colorado Boulder": {
        "rank": 91,
        "acceptance_rate": 0.814,
        "avg_gpa_unweighted": 3.65,
        "avg_gpa_weighted": 3.89,
        "sat_range": (1160, 1380),
        "sat_25th": 1160, "sat_75th": 1380,
        "act_range": (26, 32),
        "selectivity": "competitive",
        "available_rounds": ["EA", "RD"],
        "values_demonstrated_interest": False,
        "need_blind": False
    },
    "University of South Carolina": {
        "rank": 91,
        "acceptance_rate": 0.644,
        "avg_gpa_unweighted": 3.66,
        "avg_gpa_weighted": 3.90,
        "sat_range": (1180, 1360),
        "sat_25th": 1180, "sat_75th": 1360,
        "act_range": (26, 31),
        "selectivity": "competitive",
        "available_rounds": ["EA", "RD"],
        "values_demonstrated_interest": False,
        "need_blind": False
    }
}
